### ISSUE TITLE
Error when I use bracket in name

### ISSUE THREAD

**Issue by borisalmonacid** [avian2/jsonmerge#33]
------Error-----
Traceback (most recent call last):
  File "mergejson.py", line 32, in <module>
    mergejson('CFP01_C2_TIME_10_otros.json', 'CFP01_C2_TIME_10.json', 'salida.json')
  File "mergejson.py", line 23, in mergejson
    result = merger.merge(data1, data2)
  File "/usr/local/lib/python3.6/site-packages/jsonmerge/__init__.py", line 286, in merge
    return walk.descend(schema, base, head, meta).val
  File "/usr/local/lib/python3.6/site-packages/jsonmerge/__init__.py", line 78, in descend
    rv = self.work(strategy, schema, *args, **opts)
  File "/usr/local/lib/python3.6/site-packages/jsonmerge/__init__.py", line 123, in work
    rv = strategy.merge(self, base, head, schema, meta, objclass_menu=self.merger.objclass_menu, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jsonmerge/strategies.py", line 270, in merge
    base[k] = walk.descend(subschema, base.get(k), v, meta)
  File "/usr/local/lib/python3.6/site-packages/jsonmerge/__init__.py", line 78, in descend
    rv = self.work(strategy, schema, *args, **opts)
  File "/usr/local/lib/python3.6/site-packages/jsonmerge/__init__.py", line 123, in work
    rv = strategy.merge(self, base, head, schema, meta, objclass_menu=self.merger.objclass_menu, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jsonmerge/strategies.py", line 114, in merge
    raise HeadInstanceError("Head for an 'append' merge strategy is not an array", head)
**jsonmerge.exceptions.HeadInstanceError: Head for an 'append' merge strategy is not an array: #/[1]CFP01**

------Data-----
{**"[1]CFP01**":{"BAT":[{"times":[4],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4,7],"values":[2.0,0.0]},{"times":[5],"values":[0.0]},{"times":[7],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[5],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[2],"values":[0.0]},{"times":[6],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[5],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[6],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[8],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[4],"values":[0.0]}],"MBO":[{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0,44],"values":[2.0,0.0]},{"times":[0],"values":[0.0]},{"times":[0,42],"values":[2.0,0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0,40],"values":[2.0,0.0]},{"times":[0],"values":[0.0]},{"times":[0,44],"values":[2.0,0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0,43],"values":[2.0,0.0]},{"times":[0,50],"values":[2.0,0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]},{"times":[0],"values":[0.0]}],"PSO":[{"times":[4],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[2],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[2],"values":[0.0]},{"times":[2],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[2],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[2],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[3],"values":[0.0]},{"times":[4],"values":[0.0]},{"times":[3],"values":[0.0]}]}}

------ Solution (manual)
Change in the file {**"[1]CFP01"**:{"BAT ... to ... {**"CFP01"**:{"BAT ...

**Comment by avian2** [comment]
Hi. Your report doesn't have enough information for me to reproduce the issue.

```
File "mergejson.py", line 23, in mergejson
result = merger.merge(data1, data2)
```

Please include values for `data1`, `data2` and how you instantiate the merger object (including the schema if any). I would appreciate if you could narrow down your data to the minimal set that causes the issue. Thanks.
